# Generated by Django 3.2.13 on 2022-06-11 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Using UUID instead of number', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated time')),
                ('mimetype', models.CharField(help_text='Image mimetype', max_length=100)),
                ('name', models.CharField(help_text='Original file name', max_length=250)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Uploading'), (2, 'Uploaded'), (3, 'Processing'), (4, 'Processed'), (5, 'Error')], default=1, help_text='Image upload status')),
                ('message', models.TextField(blank=True, help_text='Error messages, if any', null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
