# Generated by Django 3.2.13 on 2022-06-12 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='available_extensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Image format like png, jpg, jpeg, etc', max_length=25), default=list, help_text='Store available extensions as a Array/List', size=None),
        ),
    ]
